import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import profile from '../public/images/profil.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>M. Ilyas Personal Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous"
        />

        <script
          src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
          crossorigin="anonymous"
        ></script>
      </Head>

      <main>
        <div className="container">
          <div className="row kanan">
            <div className="col-md-6">
              <div className="image">
                <Image src={profile} />
              </div>
              <div class="nama">
                <h1 class="nama__profile">MUHAMMAD ILYAS</h1>
                <h3 class="pekerjaan">FULLSTACK DEVELOPER</h3>
                <h4 class="location mt-2">Location : South Tangerang</h4>
              </div>
              <div class="summary">
                <h2>SUMMARY</h2>
                <p>
                  I am a Fullstack Developer, an ambitious problem solver with a
                  passion for web development especially frontend development
                  using Next Js (React Js). Creative developer dedicated to
                  developing and optimizing interactive, user-friendly, and
                  feature rich websites.
                </p>
                <p>
                  I enjoy being challenged and engaging with projects that
                  require me to work outside my comfort and knowledge set, as
                  continuing to learn new languages and development techniques.
                </p>
              </div>
              <div class="skill">
                <h2>PERSONAL SKILLS</h2>
                <table width="100%">
                  <thead>
                    <th colspan="4">FRONTEND</th>
                  </thead>
                  <tbody>
                    <tr>
                      <td>NextJs</td>
                      <td>ReactJs</td>
                      <td>React Native</td>
                      <td>Bootstrap</td>
                    </tr>
                    <tr>
                      <td>HTML</td>
                      <td>SASS</td>
                      <td>CSS</td>
                      <td>Javascript</td>
                    </tr>
                  </tbody>
                </table>
                <br />
                <table width="100%">
                  <thead>
                    <th colspan="4">BACKEND</th>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Laravel</td>
                      <td>ExpressJs</td>
                      <td>NodeJs</td>
                      <td>Firebase</td>
                    </tr>
                    <tr>
                      <td>MySQL</td>
                      <td>MongoDB</td>
                    </tr>
                  </tbody>
                </table>
                <br />
                <table width="100%">
                  <thead>
                    <th colspan="4">VERSION CONTROL & DEPLOYMENT</th>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Github</td>
                      <td>Gitlab</td>
                      <td>Netlify</td>
                      <td>Heroku</td>
                    </tr>
                    <tr>
                      <td>Github Pages</td>
                      <td>Vercel</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class="contact">
                <h2>REACH ME AT</h2>
                <b>Phone Number</b>
                <p>+62 822 6961 6558</p>
                <strong>Email Address</strong>
                <p>muhammadilyassaya@gmail.com</p>
              </div>

              <div class="social">
                <h2>SOCIAL MEDIA</h2>
                <table width="100%">
                  <thead>
                    <th>Website</th>
                    <th>Instagram</th>
                    <th>Github</th>
                    <th>LinkedIn</th>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="text-center py-3 px-3">
                        <a
                          href="https://milyas26.github.io/cv/"
                          target="_blank"
                        >
                          <img class="image_icon" src="/images/web.png" />
                        </a>
                      </td>

                      <td className="text-center py-3 px-3">
                        <a
                          href="https://www.instagram.com/26mill_/"
                          target="_blank"
                        >
                          <img class="image_icon" src="/images/instagram.png" />
                        </a>
                      </td>
                      <td className="text-center py-3 px-3">
                        <a href="https://github.com/milyas26" target="_blank">
                          <img class="image_icon" src="/images/github.png" />
                        </a>
                      </td>
                      <td className="text-center py-3 px-3">
                        <a
                          href="https://www.linkedin.com/in/muhilyas/"
                          target="_blank"
                        >
                          <img class="image_icon" src="/images/linkedin.png" />
                        </a>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div className="col-md-6">
              <div class="academic">
                <h2>ACADEMIC HISTORY</h2>

                <div class="training">
                  <h3>TRAINING</h3>
                  <div class="bootcamp">
                    <h4>BOOTCAMP DUMBWAYS INDONESIA</h4>
                    <i>November 2020 - December 2020</i>
                    <ul>
                      <li>
                        Learning how to build frontend websites using React Js
                      </li>
                      <li>Build RESTfull API using Express Js</li>
                      <li>Learning Mobile Development using React Native</li>
                      <li>
                        Build 2 dinamic websites and 1 mobile app for real case
                        projects
                      </li>
                    </ul>
                  </div>
                </div>

                <div class="courses">
                  <h3>COURSES</h3>
                  <div class="fullstack_javascript">
                    <h4>
                      FULLSTACK JAVASCRIPT DEVELOPER & FULLSTACK REACT NATIVE
                      DEVELOPER | BuildWith Angga
                    </h4>
                    <em>September 2020 - December 2020</em>
                    <ul>
                      <li>
                        Learning about UI/UX Design, Wireframing, Moodboard, and
                        Visual Design for mobile and web application.
                      </li>
                      <li>
                        Build real project 'Staycation Website' using MERN Stack
                        and other technologies
                      </li>
                      <li>
                        Build My Doctor App, an app for consultation with
                        personal doctor online. Using React Native, Firebase for
                        realtime chat, and other technologies.
                      </li>
                    </ul>
                  </div>

                  <div class="web_development">
                    <h4>THE COMPLETE 2020 WEB DEVELOPMENT | Udemy</h4>
                    <i>April 2020 - June 2020</i>
                    <ul>
                      <li>
                        Learning HTML, CSS, Javascript, Bootstrap, and React Js
                        for frontend
                      </li>
                      <li>
                        Build RESTfull API using Express Js and SQL Database
                        MongoDB with Mongoose
                      </li>
                      <li>Learning Authentication and Security for website</li>
                      <li>Learn about Version Control using Github</li>
                    </ul>
                  </div>
                </div>

                <div class="formal_education">
                  <h3>FORMAL EDUCATION</h3>
                  <div class="siber_asia">
                    <h4>ASIAN CYBER UNIVERSITY | Teknik Informatika</h4>
                    <em>March 2021 - March 2024</em>
                  </div>
                  <div class="sma">
                    <h4>SMAN 02 MUKOMUKO | Ilmu Pengetahuan Alam</h4>
                    <i>April 2014 - April 2017</i>
                  </div>
                </div>
              </div>
              <div class="experiences">
                <h2>WORK EXPERIENCES</h2>
                <div class="dvoretsky">
                  <h4>DVORETSKY GROUP | Fullstack Developer</h4>
                  <i>Software House | February 2021 - Now</i>
                  <ul>
                    <li>
                      Build feature rich website using Laravel, frontend
                      framework using Bootatrap, MySQL for database management,
                      and other technologies.
                    </li>
                    <li>
                      Build Frontend website from Figma design into interactive
                      website application using Next Js (React Js Framework),
                      state management using Redux, form validation using Yup,
                      and other technologies.
                    </li>
                    <li>
                      Build Rest API using Laravel and Integration API for
                      Frontend from backend.
                    </li>
                  </ul>
                </div>
                <div class="freelance">
                  <h4>FIVERR | Freelance Web Developer</h4>
                  <i>January 2020 - October 2020</i>
                  <ul>
                    <li>
                      Build static website like company profile, portfolio
                      websites and landing page using HTML, CSS, Javascript and
                      Bootstrap
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
